"""Provider-neutral semantic inference adapters.

This package is intentionally not wired into ``src.utils`` or the public agent
yet.  It supplies strict contracts and first-party HTTP transports for the
future policy broker.
"""

from .anthropic import AnthropicAdapter
from .broker import (
    BrokerCancellationPersistenceError,
    BrokerAttemptEvidence,
    BrokerDelegationResult,
    BrokerHarvestStatus,
    GrokDelegationPlan,
    GrokWorkerBroker,
    GrokWorkerBrokerResult,
    GrokWorkerDelegation,
    ProviderAttemptHarvestTrigger,
    ProviderAttemptStore,
    WorkerFallbackPolicy,
)
from .contracts import (
    BillingClass,
    CredentialPlane,
    CredentialKind,
    CredentialState,
    EndpointKind,
    GrokSupervisorBinding,
    ProviderAdapter,
    ProviderAttemptResult,
    ProviderAttemptStart,
    ProviderChannel,
    ProviderDescriptor,
    ProviderFailureReceipt,
    ProviderId,
    ProviderMessage,
    ProviderModelPins,
    ProviderReceipt,
    ProviderRequest,
    ProviderResponse,
    ProviderTokenUsage,
    RouteClass,
    WorkerAuthority,
    model_visible_messages,
)
from .errors import (
    ProviderConfigurationError,
    ProviderError,
    ProviderProtocolError,
    ProviderTransportError,
)
from .gemini import GeminiAdapter
from .openai import OpenAIAdapter
from .registry import build_provider_registry
from .subscription import (
    DISABLED_SUBSCRIPTION_SURFACES,
    CLIProcessResult,
    CLIProcessRunner,
    ClaudeCLIAdapter,
    ClientSamplingRequest,
    ClientSamplingResult,
    MCPClientSamplingAdapter,
    SamplingCallback,
    SamplingCapability,
    SamplingClientBinding,
    SamplingMessage,
    SamplingModelHint,
    SamplingModelPreferences,
    SamplingTextContent,
    build_subscription_registry,
)
from .vertex import ADCIdentity, VertexADCAdapter, load_google_adc_identity

__all__ = [
    "ADCIdentity",
    "AnthropicAdapter",
    "BillingClass",
    "BrokerAttemptEvidence",
    "BrokerCancellationPersistenceError",
    "BrokerDelegationResult",
    "BrokerHarvestStatus",
    "CLIProcessResult",
    "CLIProcessRunner",
    "ClaudeCLIAdapter",
    "ClientSamplingRequest",
    "ClientSamplingResult",
    "CredentialKind",
    "CredentialPlane",
    "CredentialState",
    "EndpointKind",
    "GeminiAdapter",
    "GrokDelegationPlan",
    "GrokSupervisorBinding",
    "GrokWorkerBroker",
    "GrokWorkerBrokerResult",
    "GrokWorkerDelegation",
    "OpenAIAdapter",
    "MCPClientSamplingAdapter",
    "ProviderAdapter",
    "ProviderAttemptHarvestTrigger",
    "ProviderAttemptResult",
    "ProviderAttemptStart",
    "ProviderAttemptStore",
    "ProviderChannel",
    "ProviderConfigurationError",
    "ProviderDescriptor",
    "ProviderError",
    "ProviderFailureReceipt",
    "ProviderId",
    "ProviderMessage",
    "ProviderModelPins",
    "ProviderProtocolError",
    "ProviderReceipt",
    "ProviderRequest",
    "ProviderResponse",
    "ProviderTokenUsage",
    "ProviderTransportError",
    "RouteClass",
    "SamplingCallback",
    "SamplingCapability",
    "SamplingClientBinding",
    "SamplingMessage",
    "SamplingModelHint",
    "SamplingModelPreferences",
    "SamplingTextContent",
    "VertexADCAdapter",
    "build_provider_registry",
    "build_subscription_registry",
    "DISABLED_SUBSCRIPTION_SURFACES",
    "load_google_adc_identity",
    "model_visible_messages",
    "WorkerAuthority",
    "WorkerFallbackPolicy",
]
