import {
  BarChart,
  Callout,
  Card,
  CardBody,
  CardHeader,
  Divider,
  Grid,
  H1,
  H2,
  Link,
  Pill,
  Row,
  Select,
  Spacer,
  Stack,
  Stat,
  Table,
  Text,
  Toggle,
  UsageBar,
  useCanvasState,
  useHostTheme,
} from "cursor/canvas";

type FileMetric = {
  file: string;
  short: string;
  before: number;
  after: number;
  parseMs: number;
  compileMs: number;
  pr: number;
  inTree?: string;
  status: "Ready" | "draft" | "in-tree";
  loop: number;
};

/** Embedded from unigrok-intelligence tracker · 2026-07-16T17:28:04Z */
const FILES: FileMetric[] = [
  {
    file: "src/utils.py",
    short: "utils.py",
    before: 13830,
    after: 800,
    parseMs: 53.0,
    compileMs: 42.0,
    pr: 342,
    status: "Ready",
    loop: 1,
  },
  {
    file: "tests/test_utils.py",
    short: "test_utils.py",
    before: 7848,
    after: 200,
    parseMs: 29.0,
    compileMs: 26.0,
    pr: 345,
    status: "Ready",
    loop: 2,
  },
  {
    file: "tests/test_provider_broker.py",
    short: "test_provider_broker.py",
    before: 4707,
    after: 150,
    parseMs: 17.0,
    compileMs: 14.0,
    pr: 346,
    status: "Ready",
    loop: 3,
  },
  {
    file: "src/providers/broker.py",
    short: "broker.py",
    before: 3122,
    after: 600,
    parseMs: 9.0,
    compileMs: 8.0,
    pr: 347,
    status: "Ready",
    loop: 4,
  },
  {
    file: "src/http_server.py",
    short: "http_server.py",
    before: 2874,
    after: 400,
    parseMs: 11.0,
    compileMs: 9.0,
    pr: 348,
    status: "Ready",
    loop: 5,
  },
  {
    file: "tests/test_http_server.py",
    short: "test_http_server.py",
    before: 2371,
    after: 150,
    parseMs: 10.0,
    compileMs: 7.0,
    pr: 349,
    status: "Ready",
    loop: 6,
  },
  {
    file: "src/intelligence_payloads.py",
    short: "intelligence_payloads.py",
    before: 1749,
    after: 120,
    parseMs: 8.0,
    compileMs: 5.0,
    pr: 350,
    status: "Ready",
    loop: 7,
  },
  {
    file: "evals/.../stage1_harness.py",
    short: "stage1_harness.py",
    before: 1644,
    after: 200,
    parseMs: 5.0,
    compileMs: 5.0,
    pr: 351,
    status: "Ready",
    loop: 8,
  },
  {
    file: "src/tools/system.py",
    short: "system.py",
    before: 1525,
    after: 120,
    parseMs: 6.0,
    compileMs: 5.0,
    pr: 352,
    status: "Ready",
    loop: 9,
  },
  {
    file: "src/providers/subscription.py",
    short: "subscription.py",
    before: 1427,
    after: 150,
    parseMs: 5.0,
    compileMs: 3.0,
    pr: 353,
    status: "Ready",
    loop: 10,
  },
  {
    file: "tests/test_mcp_session_guard.py",
    short: "test_mcp_session_guard.py",
    before: 1397,
    after: 120,
    parseMs: 6.0,
    compileMs: 5.0,
    pr: 354,
    status: "Ready",
    loop: 11,
  },
  {
    file: "tests/test_mcp_sampling_bridge.py",
    short: "test_mcp_sampling_bridge.py",
    before: 1379,
    after: 120,
    parseMs: 5.0,
    compileMs: 4.0,
    pr: 355,
    status: "Ready",
    loop: 12,
  },
  {
    file: "evals/.../attempt_ledger.py",
    short: "attempt_ledger.py",
    before: 1298,
    after: 200,
    parseMs: 4.0,
    compileMs: 4.0,
    pr: 356,
    status: "Ready",
    loop: 13,
  },
  {
    file: "tests/test_intelligence_payloads.py",
    short: "test_intelligence_payloads.py",
    before: 1278,
    after: 100,
    parseMs: 5.0,
    compileMs: 4.0,
    pr: 357,
    status: "Ready",
    loop: 14,
  },
  {
    file: "tests/test_subscription_transports.py",
    short: "test_subscription_transports.py",
    before: 1235,
    after: 100,
    parseMs: 4.0,
    compileMs: 3.0,
    pr: 358,
    status: "Ready",
    loop: 15,
  },
  {
    file: "tests/test_task_rag.py",
    short: "test_task_rag.py",
    before: 1201,
    after: 100,
    parseMs: 5.0,
    compileMs: 4.0,
    pr: 359,
    status: "Ready",
    loop: 16,
  },
  {
    file: "tests/test_provider_harvest.py",
    short: "test_provider_harvest.py",
    before: 1188,
    after: 100,
    parseMs: 5.28,
    compileMs: 4.75,
    pr: 360,
    status: "Ready",
    loop: 17,
  },
  {
    file: "src/tools/swarm.py",
    short: "swarm.py",
    before: 1155,
    after: 120,
    parseMs: 5.21,
    compileMs: 4.12,
    pr: 361,
    status: "Ready",
    loop: 18,
  },
  {
    file: "src/mcp_session_guard.py",
    short: "mcp_session_guard.py",
    before: 1105,
    after: 120,
    parseMs: 4.25,
    compileMs: 3.02,
    pr: 362,
    status: "Ready",
    loop: 19,
  },
  {
    file: "tests/test_server.py",
    short: "test_server.py",
    before: 1110,
    after: 100,
    parseMs: 3.86,
    compileMs: 3.92,
    pr: 363,
    status: "Ready",
    loop: 20,
  },
  {
    file: "tests/test_provider_adapters.py",
    short: "test_provider_adapters.py",
    before: 1061,
    after: 100,
    parseMs: 4.49,
    compileMs: 2.88,
    pr: 364,
    status: "Ready",
    loop: 21,
  },
  {
    file: "tests/test_multiagent.py",
    short: "test_multiagent.py",
    before: 1102,
    after: 100,
    parseMs: 4.4,
    compileMs: 3.52,
    pr: 365,
    status: "Ready",
    loop: 22,
  },
  {
    file: "src/rag.py",
    short: "rag.py",
    before: 1001,
    after: 150,
    parseMs: 3.37,
    compileMs: 3.01,
    pr: 366,
    status: "Ready",
    loop: 23,
  },
  {
    file: "src/providers/mcp_sampling.py",
    short: "mcp_sampling.py",
    before: 986,
    after: 120,
    parseMs: 3.13,
    compileMs: 2.66,
    pr: 367,
    status: "Ready",
    loop: 24,
  },
  {
    file: "tests/test_knowledge.py",
    short: "test_knowledge.py",
    before: 1021,
    after: 100,
    parseMs: 4.53,
    compileMs: 3.34,
    pr: 368,
    status: "Ready",
    loop: 25,
  },
  {
    file: "tests/test_evals.py",
    short: "test_evals.py",
    before: 926,
    after: 100,
    parseMs: 3.66,
    compileMs: 3.19,
    pr: 369,
    status: "Ready",
    loop: 26,
  },
  {
    file: "src/providers/contracts.py",
    short: "contracts.py",
    before: 877,
    after: 100,
    parseMs: 3.35,
    compileMs: 2.42,
    pr: 370,
    status: "Ready",
    loop: 27,
  },
  {
    file: "src/provider_harvest.py",
    short: "provider_harvest.py",
    before: 816,
    after: 120,
    parseMs: 2.54,
    compileMs: 2.14,
    pr: 371,
    status: "Ready",
    loop: 28,
  },
  {
    file: "tests/test_credentials.py",
    short: "test_credentials.py",
    before: 804,
    after: 100,
    parseMs: 2.67,
    compileMs: 2.27,
    pr: 372,
    status: "Ready",
    loop: 29,
  },
  {
    file: "src/tools/chats.py",
    short: "chats.py",
    before: 800,
    after: 100,
    parseMs: 2.35,
    compileMs: 2.0,
    pr: 373,
    status: "Ready",
    loop: 30,
  },
  {
    file: "src/completion_envelope.py",
    short: "completion_envelope.py",
    before: 791,
    after: 100,
    parseMs: 2.98,
    compileMs: 2.04,
    pr: 374,
    status: "Ready",
    loop: 31,
  },
  {
    file: "tests/test_completion_envelope.py",
    short: "test_completion_envelope.py",
    before: 733,
    after: 90,
    parseMs: 2.48,
    compileMs: 1.83,
    pr: 375,
    status: "Ready",
    loop: 32,
  },
  {
    file: "tests/.../test_stage1_schema_safety.py",
    short: "test_stage1_schema_safety.py",
    before: 721,
    after: 90,
    parseMs: 1.99,
    compileMs: 1.95,
    pr: 376,
    status: "Ready",
    loop: 33,
  },
  {
    file: "tests/test_provider_attempt_ledger.py",
    short: "test_provider_attempt_ledger.py",
    before: 714,
    after: 90,
    parseMs: 2.48,
    compileMs: 1.86,
    pr: 377,
    status: "Ready",
    loop: 34,
  },
  {
    file: "tests/test_mcp_ui.py",
    short: "test_mcp_ui.py",
    before: 730,
    after: 90,
    parseMs: 2.93,
    compileMs: 2.07,
    pr: 378,
    status: "Ready",
    loop: 35,
  },
  {
    file: "tests/test_observability.py",
    short: "test_observability.py",
    before: 712,
    after: 90,
    parseMs: 2.51,
    compileMs: 2.13,
    pr: 379,
    status: "Ready",
    loop: 36,
  },
  {
    file: "tests/test_migrations.py",
    short: "test_migrations.py",
    before: 696,
    after: 90,
    parseMs: 2.38,
    compileMs: 1.59,
    pr: 380,
    status: "Ready",
    loop: 37,
  },
  {
    file: "src/workspace_memory.py",
    short: "workspace_memory.py",
    before: 668,
    after: 100,
    parseMs: 3.19,
    compileMs: 2.47,
    pr: 381,
    status: "Ready",
    loop: 38,
  },
  {
    file: "evals/runner.py",
    short: "runner.py",
    before: 659,
    after: 100,
    parseMs: 3.25,
    compileMs: 2.63,
    pr: 382,
    status: "Ready",
    loop: 39,
  },
  {
    file: "evals/.../provider_adapters.py",
    short: "provider_adapters.py",
    before: 623,
    after: 80,
    parseMs: 2.46,
    compileMs: 1.69,
    pr: 383,
    status: "Ready",
    loop: 40,
  },
  {
    file: "tests/.../test_attempt_ledger_safety.py",
    short: "test_attempt_ledger_safety.py",
    before: 612,
    after: 80,
    parseMs: 2.4,
    compileMs: 1.88,
    pr: 384,
    status: "Ready",
    loop: 41,
  },
  {
    file: "src/swarm/engine.py",
    short: "engine.py",
    before: 570,
    after: 80,
    parseMs: 2.33,
    compileMs: 1.62,
    pr: 385,
    status: "Ready",
    loop: 42,
  },
  {
    file: "tests/test_phase5.py",
    short: "test_phase5.py",
    before: 798,
    after: 90,
    parseMs: 2.98,
    compileMs: 2.19,
    pr: 386,
    status: "Ready",
    loop: 43,
  },
  {
    file: "tests/test_service_workspace_boundary.py",
    short: "test_service_workspace_boundary.py",
    before: 580,
    after: 80,
    parseMs: 2.28,
    compileMs: 1.73,
    pr: 387,
    status: "Ready",
    loop: 44,
  },
  {
    file: "evals/.../role_schemas.py",
    short: "role_schemas.py",
    before: 559,
    after: 70,
    parseMs: 2.08,
    compileMs: 1.48,
    pr: 388,
    status: "Ready",
    loop: 45,
  },
  {
    file: "evals/.../schemas.py",
    short: "schemas.py",
    before: 558,
    after: 70,
    parseMs: 1.65,
    compileMs: 1.41,
    pr: 389,
    status: "Ready",
    loop: 46,
  },
  {
    file: "tests/test_swarm_tools.py",
    short: "test_swarm_tools.py",
    before: 539,
    after: 70,
    parseMs: 2.5,
    compileMs: 1.65,
    pr: 390,
    status: "Ready",
    loop: 47,
  },
  {
    file: "src/intelligence_capsule.py",
    short: "intelligence_capsule.py",
    before: 539,
    after: 70,
    parseMs: 2.2,
    compileMs: 1.81,
    pr: 391,
    status: "Ready",
    loop: 48,
  },
  {
    file: "tests/.../test_provider_contract.py",
    short: "test_provider_contract.py",
    before: 533,
    after: 70,
    parseMs: 1.94,
    compileMs: 1.39,
    pr: 392,
    status: "Ready",
    loop: 49,
  },
  {
    file: "tests/test_intelligence_upgrade.py",
    short: "test_intelligence_upgrade.py",
    before: 549,
    after: 70,
    parseMs: 1.49,
    compileMs: 1.41,
    pr: 393,
    status: "Ready",
    loop: 50,
  },
  {
    file: "evals/.../provider_smoke.py",
    short: "provider_smoke.py",
    before: 491,
    after: 60,
    parseMs: 1.91,
    compileMs: 1.43,
    pr: 394,
    status: "Ready",
    loop: 51,
  },
  {
    file: "tests/test_swarm_engine.py",
    short: "test_swarm_engine.py",
    before: 481,
    after: 60,
    parseMs: 2.27,
    compileMs: 1.52,
    pr: 395,
    status: "Ready",
    loop: 52,
  },
  {
    file: "scripts/install_unigrok_theme.py",
    short: "install_unigrok_theme.py",
    before: 478,
    after: 60,
    parseMs: 1.81,
    compileMs: 1.36,
    pr: 396,
    status: "Ready",
    loop: 53,
  },
  {
    file: "tests/.../test_stage1_mock_harness.py",
    short: "test_stage1_mock_harness.py",
    before: 477,
    after: 60,
    parseMs: 2.22,
    compileMs: 1.5,
    pr: 397,
    status: "Ready",
    loop: 54,
  },
  {
    file: "scripts/land.py",
    short: "land.py",
    before: 489,
    after: 70,
    parseMs: 1.84,
    compileMs: 1.53,
    pr: 398,
    status: "Ready",
    loop: 55,
  },
  {
    file: "tests/test_release_hygiene.py",
    short: "test_release_hygiene.py",
    before: 468,
    after: 60,
    parseMs: 2.13,
    compileMs: 1.46,
    pr: 399,
    status: "Ready",
    loop: 56,
  },
  {
    file: "evals/.../validators.py",
    short: "validators.py",
    before: 465,
    after: 50,
    parseMs: 1.46,
    compileMs: 1.61,
    pr: 400,
    status: "Ready",
    loop: 57,
  },
  {
    file: "src/semantic_evals.py",
    short: "semantic_evals.py",
    before: 463,
    after: 60,
    parseMs: 1.18,
    compileMs: 1.14,
    pr: 401,
    status: "Ready",
    loop: 58,
  },
  {
    file: "tests/test_github_review_integration.py",
    short: "test_github_review_integration.py",
    before: 484,
    after: 60,
    parseMs: 1.57,
    compileMs: 1.25,
    pr: 402,
    status: "Ready",
    loop: 59,
  },
  {
    file: "tests/test_semantic_evals.py",
    short: "test_semantic_evals.py",
    before: 441,
    after: 55,
    parseMs: 1.75,
    compileMs: 1.31,
    pr: 403,
    status: "Ready",
    loop: 60,
  },
  {
    file: "scripts/bootstrap_intelligence_refs.py",
    short: "bootstrap_intelligence_refs.py",
    before: 435,
    after: 55,
    parseMs: 1.84,
    compileMs: 1.28,
    pr: 404,
    status: "Ready",
    loop: 61,
  },
  {
    file: "scripts/supervisor_approval.py",
    short: "supervisor_approval.py",
    before: 394,
    after: 50,
    parseMs: 1.65,
    compileMs: 1.75,
    pr: 405,
    status: "Ready",
    loop: 62,
  },
  {
    file: "src/metrics.py",
    short: "metrics.py",
    before: 422,
    after: 55,
    parseMs: 1.64,
    compileMs: 1.46,
    pr: 406,
    status: "Ready",
    loop: 63,
  },
  {
    file: "tests/.../test_provider_smoke.py",
    short: "test_provider_smoke.py",
    before: 407,
    after: 50,
    parseMs: 1.36,
    compileMs: 1.09,
    pr: 407,
    status: "Ready",
    loop: 64,
  },
  {
    file: "tests/test_install_unigrok_theme.py",
    short: "test_install_unigrok_theme.py",
    before: 395,
    after: 50,
    parseMs: 1.25,
    compileMs: 0.87,
    pr: 409,
    status: "Ready",
    loop: 65,
  },
  {
    file: "tests/test_intelligence_refs_bootstrap.py",
    short: "test_intelligence_refs_bootstrap.py",
    before: 389,
    after: 50,
    parseMs: 1.5,
    compileMs: 1.39,
    pr: 410,
    status: "Ready",
    loop: 66,
  },
  {
    file: "tests/test_metrics.py",
    short: "test_metrics.py",
    before: 388,
    after: 50,
    parseMs: 1.93,
    compileMs: 1.26,
    pr: 411,
    status: "Ready",
    loop: 67,
  },
  {
    file: "src/providers/base.py",
    short: "base.py",
    before: 380,
    after: 45,
    parseMs: 1.11,
    compileMs: 1.05,
    pr: 412,
    status: "Ready",
    loop: 68,
  },
  {
    file: "scripts/check_agent_attribution.py",
    short: "check_agent_attribution.py",
    before: 369,
    after: 45,
    parseMs: 1.69,
    compileMs: 1.54,
    pr: 413,
    status: "Ready",
    loop: 69,
  },
  {
    file: "tests/test_workspace_memory.py",
    short: "test_workspace_memory.py",
    before: 365,
    after: 45,
    parseMs: 1.75,
    compileMs: 1.14,
    pr: 414,
    status: "Ready",
    loop: 70,
  },
  {
    file: "scripts/github-grok-review.py",
    short: "github-grok-review.py",
    before: 350,
    after: 45,
    parseMs: 1.61,
    compileMs: 1.46,
    pr: 415,
    status: "Ready",
    loop: 71,
  },
  {
    file: "src/jobs.py",
    short: "jobs.py",
    before: 381,
    after: 45,
    parseMs: 1.23,
    compileMs: 1.5,
    pr: 416,
    status: "Ready",
    loop: 72,
  },
  {
    file: "tests/test_land_workflow.py",
    short: "test_land_workflow.py",
    before: 388,
    after: 45,
    parseMs: 2.01,
    compileMs: 1.7,
    pr: 417,
    status: "Ready",
    loop: 73,
  },
  {
    file: "tests/test_xai_client_authority.py",
    short: "test_xai_client_authority.py",
    before: 334,
    after: 45,
    parseMs: 1.13,
    compileMs: 1.02,
    pr: 418,
    status: "Ready",
    loop: 74,
  },
  {
    file: "src/storage.py",
    short: "storage.py",
    before: 342,
    after: 40,
    parseMs: 1.27,
    compileMs: 0.98,
    pr: 419,
    status: "Ready",
    loop: 75,
  },
  {
    file: "tests/test_swarm_storage.py",
    short: "test_swarm_storage.py",
    before: 312,
    after: 40,
    parseMs: 1.32,
    compileMs: 1.1,
    pr: 420,
    status: "Ready",
    loop: 76,
  },
  {
    file: "tests/test_supervisor_approval.py",
    short: "test_supervisor_approval.py",
    before: 326,
    after: 40,
    parseMs: 0.99,
    compileMs: 0.7,
    pr: 421,
    status: "Ready",
    loop: 77,
  },
  {
    file: "src/swarm/analytics.py",
    short: "analytics.py",
    before: 299,
    after: 40,
    parseMs: 1.85,
    compileMs: 1.15,
    pr: 423,
    status: "Ready",
    loop: 78,
  },
  {
    file: "evals/.../stage1_oracles.py",
    short: "stage1_oracles.py",
    before: 297,
    after: 40,
    parseMs: 1.05,
    compileMs: 0.78,
    pr: 424,
    status: "Ready",
    loop: 79,
  },
  {
    file: "src/swarm/sandbox.py",
    short: "sandbox.py",
    before: 296,
    after: 35,
    parseMs: 1.06,
    compileMs: 0.9,
    pr: 425,
    status: "Ready",
    loop: 80,
  },
  {
    file: "src/tools/media.py",
    short: "media.py",
    before: 290,
    after: 35,
    parseMs: 1.0,
    compileMs: 0.85,
    pr: 426,
    status: "Ready",
    loop: 81,
  },
  {
    file: "scripts/run_swarm_evals.py",
    short: "run_swarm_evals.py",
    before: 286,
    after: 35,
    parseMs: 1.43,
    compileMs: 1.08,
    pr: 427,
    status: "Ready",
    loop: 82,
  },
  {
    file: "tests/test_routing.py",
    short: "test_routing.py",
    before: 277,
    after: 35,
    parseMs: 0.95,
    compileMs: 0.79,
    pr: 428,
    status: "Ready",
    loop: 83,
  },
  {
    file: "evals/.../provider_transports.py",
    short: "provider_transports.py",
    before: 273,
    after: 35,
    parseMs: 0.86,
    compileMs: 1.13,
    pr: 429,
    status: "Ready",
    loop: 84,
  },
  {
    file: "src/routing.py",
    short: "routing.py",
    before: 272,
    after: 35,
    parseMs: 1.3,
    compileMs: 0.9,
    pr: 430,
    status: "Ready",
    loop: 85,
  },
  {
    file: "src/tools/resources.py",
    short: "resources.py",
    before: 266,
    after: 35,
    parseMs: 0.82,
    compileMs: 0.68,
    pr: 431,
    status: "Ready",
    loop: 86,
  },
  {
    file: "src/tools/git.py",
    short: "git.py",
    before: 258,
    after: 35,
    parseMs: 1.36,
    compileMs: 0.97,
    pr: 432,
    status: "Ready",
    loop: 87,
  },
  {
    file: "src/faq.py",
    short: "faq.py",
    before: 253,
    after: 35,
    parseMs: 0.99,
    compileMs: 0.96,
    pr: 433,
    status: "Ready",
    loop: 88,
  },
  {
    file: "tests/test_swarm_static_gate.py",
    short: "test_swarm_static_gate.py",
    before: 250,
    after: 35,
    parseMs: 0.96,
    compileMs: 0.82,
    pr: 434,
    status: "Ready",
    loop: 89,
  },
  {
    file: "tests/test_agent_attribution.py",
    short: "test_agent_attribution.py",
    before: 247,
    after: 35,
    parseMs: 1.01,
    compileMs: 0.52,
    pr: 435,
    status: "Ready",
    loop: 90,
  },
  {
    file: "tests/test_swarm_sandbox.py",
    short: "test_swarm_sandbox.py",
    before: 243,
    after: 35,
    parseMs: 0.95,
    compileMs: 0.86,
    pr: 436,
    status: "Ready",
    loop: 91,
  },
  {
    file: "scripts/generate_okf.py",
    short: "generate_okf.py",
    before: 240,
    after: 35,
    parseMs: 1.33,
    compileMs: 1.0,
    pr: 437,
    status: "Ready",
    loop: 92,
  },
  {
    file: "evals/fakes.py",
    short: "fakes.py",
    before: 235,
    after: 35,
    parseMs: 0.79,
    compileMs: 0.69,
    pr: 438,
    status: "Ready",
    loop: 93,
  },
  {
    file: "scripts/publish_okf_wiki_mirror.py",
    short: "publish_okf_wiki_mirror.py",
    before: 234,
    after: 35,
    parseMs: 0.92,
    compileMs: 0.79,
    pr: 439,
    status: "Ready",
    loop: 94,
  },
  {
    file: "evals/.../stage1_artifacts.py",
    short: "stage1_artifacts.py",
    before: 231,
    after: 35,
    parseMs: 0.99,
    compileMs: 0.66,
    pr: 440,
    status: "Ready",
    loop: 95,
  },
  {
    file: "src/swarm/runner.py",
    short: "runner.py",
    before: 228,
    after: 35,
    parseMs: 0.78,
    compileMs: 0.68,
    pr: 441,
    status: "Ready",
    loop: 96,
  },
  {
    file: "scripts/mint_mcp_service_token.py",
    short: "mint_mcp_service_token.py",
    before: 228,
    after: 35,
    parseMs: 0.92,
    compileMs: 0.66,
    pr: 442,
    status: "Ready",
    loop: 97,
  },
  {
    file: "tests/test_harness.py",
    short: "test_harness.py",
    before: 231,
    after: 35,
    parseMs: 0.83,
    compileMs: 0.67,
    pr: 443,
    status: "Ready",
    loop: 98,
  },
  {
    file: "src/providers/vertex.py",
    short: "vertex.py",
    before: 224,
    after: 35,
    parseMs: 0.95,
    compileMs: 0.63,
    pr: 444,
    status: "Ready",
    loop: 99,
  },
  {
    file: "tests/test_markdown_renderer.py",
    short: "test_markdown_renderer.py",
    before: 213,
    after: 35,
    parseMs: 0.57,
    compileMs: 0.49,
    pr: 445,
    status: "Ready",
    loop: 100,
  },
  {
    file: "src/swarm/ast_utils.py",
    short: "ast_utils.py",
    before: 213,
    after: 35,
    parseMs: 1.06,
    compileMs: 0.7,
    pr: 446,
    status: "Ready",
    loop: 101,
  },
  {
    file: "src/credentials.py",
    short: "credentials.py",
    before: 285,
    after: 35,
    parseMs: 0.87,
    compileMs: 0.68,
    pr: 447,
    status: "Ready",
    loop: 102,
  },
  {
    file: "tests/test_agent_mode_plane_contract.py",
    short: "test_agent_mode_plane_contract.py",
    before: 209,
    after: 35,
    parseMs: 0.79,
    compileMs: 0.84,
    pr: 448,
    status: "Ready",
    loop: 103,
  },
  {
    file: "src/swarm/preflight.py",
    short: "preflight.py",
    before: 203,
    after: 35,
    parseMs: 0.8,
    compileMs: 0.61,
    pr: 449,
    status: "Ready",
    loop: 104,
  },
  {
    file: "tests/test_intelligence_capsule.py",
    short: "test_intelligence_capsule.py",
    before: 200,
    after: 35,
    parseMs: 0.64,
    compileMs: 0.64,
    pr: 450,
    status: "Ready",
    loop: 105,
  },
  {
    file: "tests/.../test_stage0_mechanical.py",
    short: "test_stage0_mechanical.py",
    before: 194,
    after: 35,
    parseMs: 0.5,
    compileMs: 0.42,
    pr: 451,
    status: "Ready",
    loop: 106,
  },
  {
    file: "src/hydration.py",
    short: "hydration.py",
    before: 194,
    after: 35,
    parseMs: 0.88,
    compileMs: 0.7,
    pr: 452,
    status: "Ready",
    loop: 107,
  },
  {
    file: "src/swarm/transforms.py",
    short: "transforms.py",
    before: 193,
    after: 35,
    parseMs: 0.77,
    compileMs: 0.68,
    pr: 453,
    status: "Ready",
    loop: 108,
  },
  {
    file: "evals/__main__.py",
    short: "__main__.py",
    before: 193,
    after: 35,
    parseMs: 0.82,
    compileMs: 0.56,
    pr: 454,
    status: "Ready",
    loop: 109,
  },
  {
    file: "tests/test_dual_plane_model_discipline.py",
    short: "test_dual_plane_model_discipline.py",
    before: 186,
    after: 35,
    parseMs: 0.72,
    compileMs: 0.65,
    pr: 455,
    status: "Ready",
    loop: 110,
  },
  {
    file: "src/cli.py",
    short: "cli.py",
    before: 268,
    after: 35,
    parseMs: 1.24,
    compileMs: 0.83,
    pr: 456,
    status: "Ready",
    loop: 111,
  },
  {
    file: "tests/test_mint_mcp_service_token.py",
    short: "test_mint_mcp_service_token.py",
    before: 174,
    after: 35,
    parseMs: 0.79,
    compileMs: 0.6,
    pr: 457,
    status: "Ready",
    loop: 112,
  },
  {
    file: "src/server.py",
    short: "server.py",
    before: 171,
    after: 35,
    parseMs: 0.39,
    compileMs: 0.26,
    pr: 458,
    status: "Ready",
    loop: 113,
  },
  {
    file: "src/providers/__init__.py",
    short: "__init__.py",
    before: 170,
    after: 35,
    parseMs: 0.24,
    compileMs: 0.2,
    pr: 459,
    status: "Ready",
    loop: 114,
  },
  {
    file: "src/swarm/pareto.py",
    short: "pareto.py",
    before: 169,
    after: 35,
    parseMs: 0.77,
    compileMs: 0.72,
    pr: 460,
    status: "Ready",
    loop: 115,
  },
  {
    file: "src/identity.py",
    short: "identity.py",
    before: 165,
    after: 35,
    parseMs: 0.51,
    compileMs: 0.42,
    pr: 461,
    status: "Ready",
    loop: 116,
  },
  {
    file: "src/swarm/mutators.py",
    short: "mutators.py",
    before: 160,
    after: 35,
    parseMs: 0.54,
    compileMs: 0.34,
    pr: 462,
    status: "Ready",
    loop: 117,
  },
  {
    file: "src/swarm/config.py",
    short: "config.py",
    before: 156,
    after: 35,
    parseMs: 0.4,
    compileMs: 0.38,
    pr: 463,
    status: "Ready",
    loop: 118,
  },
  {
    file: "src/providers/openai.py",
    short: "openai.py",
    before: 154,
    after: 35,
    parseMs: 0.49,
    compileMs: 0.43,
    pr: 464,
    status: "Ready",
    loop: 119,
  },
  {
    file: "src/tools/workspace_memory.py",
    short: "workspace_memory.py",
    before: 151,
    after: 35,
    parseMs: 0.41,
    compileMs: 0.37,
    pr: 465,
    status: "Ready",
    loop: 120,
  },
  {
    file: "src/providers/anthropic.py",
    short: "anthropic.py",
    before: 151,
    after: 35,
    parseMs: 0.43,
    compileMs: 0.45,
    pr: 466,
    status: "Ready",
    loop: 121,
  },
  {
    file: "evals/cassettes.py",
    short: "cassettes.py",
    before: 151,
    after: 35,
    parseMs: 0.77,
    compileMs: 0.55,
    pr: 470,
    status: "Ready",
    loop: 122,
  },
  {
    file: "tests/test_swarm_eval_script.py",
    short: "test_swarm_eval_script.py",
    before: 150,
    after: 35,
    parseMs: 0.51,
    compileMs: 0.47,
    pr: 471,
    status: "Ready",
    loop: 123,
  },
  {
    file: "tests/test_git_tools.py",
    short: "test_git_tools.py",
    before: 148,
    after: 35,
    parseMs: 0.51,
    compileMs: 0.48,
    pr: 472,
    status: "Ready",
    loop: 124,
  },
  {
    file: "src/tools/knowledge.py",
    short: "knowledge.py",
    before: 148,
    after: 35,
    parseMs: 0.44,
    compileMs: 0.37,
    pr: 473,
    status: "Ready",
    loop: 125,
  },
  {
    file: "tests/test_hydration.py",
    short: "test_hydration.py",
    before: 137,
    after: 35,
    parseMs: 0.37,
    compileMs: 0.32,
    pr: 474,
    status: "Ready",
    loop: 126,
  },
  {
    file: "tests/test_swarm_pareto.py",
    short: "test_swarm_pareto.py",
    before: 134,
    after: 35,
    parseMs: 0.86,
    compileMs: 0.71,
    pr: 0,
    inTree: "9fbaa2e44a53",
    status: "in-tree",
    loop: 127,
  },
  {
    file: "tests/test_swarm_ast.py",
    short: "test_swarm_ast.py",
    before: 128,
    after: 35,
    parseMs: 0.61,
    compileMs: 0.5,
    pr: 0,
    inTree: "8eef324330b2",
    status: "in-tree",
    loop: 128,
  },
  {
    file: "evals/.../mechanical_mutators.py",
    short: "mechanical_mutators.py",
    before: 124,
    after: 35,
    parseMs: 0.53,
    compileMs: 0.33,
    pr: 0,
    inTree: "174ebdc2a16e",
    status: "in-tree",
    loop: 129,
  },
  {
    file: "tests/.../test_stage1_artifacts.py",
    short: "test_stage1_artifacts.py",
    before: 119,
    after: 35,
    parseMs: 0.75,
    compileMs: 0.51,
    pr: 0,
    inTree: "249927d7259c",
    status: "in-tree",
    loop: 130,
  },
  {
    file: "src/providers/gemini.py",
    short: "gemini.py",
    before: 119,
    after: 35,
    parseMs: 0.44,
    compileMs: 0.3,
    pr: 0,
    inTree: "89ae6efbf89d",
    status: "in-tree",
    loop: 131,
  },
  {
    file: "tests/test_subagent_surface_contract.py",
    short: "test_subagent_surface_contract.py",
    before: 118,
    after: 35,
    parseMs: 0.53,
    compileMs: 0.45,
    pr: 0,
    inTree: "90f46e92039f",
    status: "in-tree",
    loop: 132,
  },
  {
    file: "src/providers/config.py",
    short: "config.py",
    before: 118,
    after: 35,
    parseMs: 0.52,
    compileMs: 0.34,
    pr: 0,
    inTree: "e75eb511c863",
    status: "in-tree",
    loop: 133,
  },
  {
    file: "src/swarm/router.py",
    short: "router.py",
    before: 116,
    after: 35,
    parseMs: 0.52,
    compileMs: 0.45,
    pr: 0,
    inTree: "76f9ee3357f1",
    status: "in-tree",
    loop: 134,
  },
  {
    file: "tests/test_phase4.py",
    short: "test_phase4.py",
    before: 114,
    after: 35,
    parseMs: 0.53,
    compileMs: 0.39,
    pr: 0,
    inTree: "589cda906ebd",
    status: "in-tree",
    loop: 135,
  },
  {
    file: "tests/test_faq.py",
    short: "test_faq.py",
    before: 111,
    after: 35,
    parseMs: 0.4,
    compileMs: 0.3,
    pr: 0,
    inTree: "aa1386cc99a7",
    status: "in-tree",
    loop: 136,
  },
  {
    file: "tests/test_export_pr.py",
    short: "test_export_pr.py",
    before: 107,
    after: 35,
    parseMs: 0.52,
    compileMs: 0.33,
    pr: 0,
    inTree: "5dbe898ffe20",
    status: "in-tree",
    loop: 137,
  },
  {
    file: "evals/graders.py",
    short: "graders.py",
    before: 102,
    after: 35,
    parseMs: 0.81,
    compileMs: 0.5,
    pr: 0,
    inTree: "22afc119170b",
    status: "in-tree",
    loop: 138,
  },
  {
    file: "src/providers/google_common.py",
    short: "google_common.py",
    before: 101,
    after: 35,
    parseMs: 0.48,
    compileMs: 0.35,
    pr: 0,
    inTree: "7547193af176",
    status: "in-tree",
    loop: 139,
  },
  {
    file: "src/swarm/static_gate.py",
    short: "static_gate.py",
    before: 99,
    after: 35,
    parseMs: 0.36,
    compileMs: 0.27,
    pr: 0,
    inTree: "38e6510976f2",
    status: "in-tree",
    loop: 140,
  },
  {
    file: "src/tools/consistency.py",
    short: "consistency.py",
    before: 98,
    after: 35,
    parseMs: 0.42,
    compileMs: 0.32,
    pr: 0,
    inTree: "9d4ccaa4a97c",
    status: "in-tree",
    loop: 141,
  },
  {
    file: "tests/test_swarm_router.py",
    short: "test_swarm_router.py",
    before: 94,
    after: 35,
    parseMs: 0.6,
    compileMs: 0.43,
    pr: 0,
    inTree: "e4e0277dec35",
    status: "in-tree",
    loop: 142,
  },
  {
    file: "tests/test_generate_okf.py",
    short: "test_generate_okf.py",
    before: 92,
    after: 35,
    parseMs: 0.38,
    compileMs: 0.23,
    pr: 0,
    inTree: "d354ee1abe72",
    status: "in-tree",
    loop: 143,
  },
  {
    file: "tests/test_publish_okf_wiki_mirror.py",
    short: "test_publish_okf_wiki_mirror.py",
    before: 89,
    after: 35,
    parseMs: 0.55,
    compileMs: 0.42,
    pr: 0,
    inTree: "3086f3c0eb4e",
    status: "in-tree",
    loop: 144,
  },
  {
    file: "scripts/land-status.py",
    short: "land-status.py",
    before: 87,
    after: 35,
    parseMs: 0.53,
    compileMs: 0.37,
    pr: 0,
    inTree: "c8b01cde5c3e",
    status: "in-tree",
    loop: 145,
  },
  {
    file: "src/tools/research.py",
    short: "research.py",
    before: 108,
    after: 35,
    parseMs: 0.41,
    compileMs: 0.27,
    pr: 0,
    inTree: "9c3becda4adc",
    status: "in-tree",
    loop: 146,
  },
  {
    file: "src/swarm/fold.py",
    short: "fold.py",
    before: 84,
    after: 35,
    parseMs: 0.47,
    compileMs: 0.28,
    pr: 0,
    inTree: "7e088b970bb7",
    status: "in-tree",
    loop: 147,
  },
  {
    file: "src/swarm/generate.py",
    short: "generate.py",
    before: 83,
    after: 35,
    parseMs: 0.36,
    compileMs: 0.24,
    pr: 0,
    inTree: "1162a515fc2a",
    status: "in-tree",
    loop: 148,
  },
  {
    file: "tests/test_swarm_analytics.py",
    short: "test_swarm_analytics.py",
    before: 81,
    after: 35,
    parseMs: 0.42,
    compileMs: 0.28,
    pr: 0,
    inTree: "dc71110a82d0",
    status: "in-tree",
    loop: 149,
  },
  {
    file: "tests/test_cli.py",
    short: "test_cli.py",
    before: 208,
    after: 35,
    parseMs: 0.96,
    compileMs: 0.79,
    pr: 0,
    inTree: "75cd0b8152c2",
    status: "in-tree",
    loop: 150,
  },
  {
    file: "src/tools/faq.py",
    short: "faq.py",
    before: 77,
    after: 35,
    parseMs: 0.26,
    compileMs: 0.18,
    pr: 0,
    inTree: "3cba81e288a7",
    status: "in-tree",
    loop: 151,
  },
  {
    file: "src/models/results.py",
    short: "results.py",
    before: 70,
    after: 35,
    parseMs: 0.53,
    compileMs: 0.36,
    pr: 0,
    inTree: "7518266f0888",
    status: "in-tree",
    loop: 152,
  },
  {
    file: "tests/test_public_intelligence_packs.py",
    short: "test_public_intelligence_packs.py",
    before: 64,
    after: 35,
    parseMs: 0.39,
    compileMs: 0.26,
    pr: 0,
    inTree: "06d02b0228da",
    status: "in-tree",
    loop: 153,
  },
  {
    file: "scripts/swarm_bench.py",
    short: "swarm_bench.py",
    before: 62,
    after: 35,
    parseMs: 0.35,
    compileMs: 0.23,
    pr: 0,
    inTree: "731c1d079d85",
    status: "in-tree",
    loop: 154,
  },
  {
    file: "src/xai_credentials.py",
    short: "xai_credentials.py",
    before: 59,
    after: 35,
    parseMs: 0.26,
    compileMs: 0.17,
    pr: 0,
    inTree: "9efbf11253a8",
    status: "in-tree",
    loop: 155,
  },
  {
    file: "tests/test_swarm_transforms.py",
    short: "test_swarm_transforms.py",
    before: 51,
    after: 35,
    parseMs: 0.21,
    compileMs: 0.14,
    pr: 0,
    inTree: "ac20d505e963",
    status: "in-tree",
    loop: 156,
  },
  {
    file: "tests/test_consistency.py",
    short: "test_consistency.py",
    before: 52,
    after: 35,
    parseMs: 0.36,
    compileMs: 0.18,
    pr: 0,
    inTree: "17327cfa2db6",
    status: "in-tree",
    loop: 157,
  },
  {
    file: "tests/test_codex_desktop_session_contract.py",
    short: "test_codex_desktop_session_contract.py",
    before: 51,
    after: 35,
    parseMs: 0.9,
    compileMs: 0.16,
    pr: 0,
    inTree: "655fcc93b0cb",
    status: "in-tree",
    loop: 158,
  },
  {
    file: "src/providers/registry.py",
    short: "registry.py",
    before: 49,
    after: 35,
    parseMs: 0.2,
    compileMs: 0.14,
    pr: 0,
    inTree: "a295ff8c3f77",
    status: "in-tree",
    loop: 159,
  },
  {
    file: "evals/tasks/swarm_targets/nsquared_dedup/test_dedup.py",
    short: "test_dedup.py",
    before: 43,
    after: 35,
    parseMs: 0.24,
    compileMs: 0.21,
    pr: 0,
    inTree: "e2e7fa2476ef",
    status: "in-tree",
    loop: 160,
  },
  {
    file: "tests/conftest.py",
    short: "conftest.py",
    before: 42,
    after: 35,
    parseMs: 0.26,
    compileMs: 0.18,
    pr: 0,
    inTree: "668855c76789",
    status: "in-tree",
    loop: 161,
  },
  {
    file: "tests/test_swarm_runner.py",
    short: "test_swarm_runner.py",
    before: 40,
    after: 20,
    parseMs: 0.38,
    compileMs: 0.19,
    pr: 0,
    inTree: "e3108c60b013",
    status: "in-tree",
    loop: 162,
  },
  {
    file: "src/providers/errors.py",
    short: "errors.py",
    before: 39,
    after: 20,
    parseMs: 0.22,
    compileMs: 0.13,
    pr: 0,
    inTree: "aad393a5f31f",
    status: "in-tree",
    loop: 163,
  },
  {
    file: ".cursor/hooks/before-unigrok-agent.py",
    short: "before-unigrok-agent.py",
    before: 39,
    after: 20,
    parseMs: 0.19,
    compileMs: 0.11,
    pr: 0,
    inTree: "9fb19b379835",
    status: "in-tree",
    loop: 164,
  },
  {
    file: "src/provider_redaction.py",
    short: "provider_redaction.py",
    before: 37,
    after: 20,
    parseMs: 0.21,
    compileMs: 0.14,
    pr: 0,
    inTree: "31faf0b2089b",
    status: "in-tree",
    loop: 165,
  },
  {
    file: "tests/test_namespace_human_radio_roots.py",
    short: "test_namespace_human_radio_roots.py",
    before: 35,
    after: 20,
    parseMs: 0.22,
    compileMs: 0.13,
    pr: 0,
    inTree: "620ff189f855",
    status: "in-tree",
    loop: 166,
  },
  {
    file: ".cursor/hooks/session-unigrok-env.py",
    short: "session-unigrok-env.py",
    before: 35,
    after: 20,
    parseMs: 0.16,
    compileMs: 0.1,
    pr: 0,
    inTree: "b4a7f83a5a29",
    status: "in-tree",
    loop: 167,
  },
  {
    file: "tests/fixtures/swarm_target/slow_mod.py",
    short: "slow_mod.py",
    before: 34,
    after: 20,
    parseMs: 0.24,
    compileMs: 0.13,
    pr: 0,
    inTree: "94ca0493bd62",
    status: "in-tree",
    loop: 168,
  },
  {
    file: "tests/test_codeql_contracts.py",
    short: "test_codeql_contracts.py",
    before: 33,
    after: 20,
    parseMs: 0.22,
    compileMs: 0.13,
    pr: 0,
    inTree: "fc7288947e75",
    status: "in-tree",
    loop: 169,
  },
  {
    file: "tests/test_okf_vscode_guidance.py",
    short: "test_okf_vscode_guidance.py",
    before: 32,
    after: 20,
    parseMs: 0.21,
    compileMs: 0.12,
    pr: 0,
    inTree: "1c812462c432",
    status: "in-tree",
    loop: 170,
  },
  {
    file: "tests/test_okf_copilot_playbook.py",
    short: "test_okf_copilot_playbook.py",
    before: 30,
    after: 20,
    parseMs: 0.18,
    compileMs: 0.12,
    pr: 0,
    inTree: "e6000ec7c726",
    status: "in-tree",
    loop: 171,
  },
  {
    file: "tests/test_okf_team_check.py",
    short: "test_okf_team_check.py",
    before: 29,
    after: 20,
    parseMs: 0.23,
    compileMs: 0.12,
    pr: 0,
    inTree: "995967d6f0ac",
    status: "in-tree",
    loop: 172,
  },
  {
    file: "tests/test_campaign.py",
    short: "test_campaign.py",
    before: 25,
    after: 20,
    parseMs: 0.29,
    compileMs: 0.15,
    pr: 0,
    inTree: "bfe42f4d9b9f",
    status: "in-tree",
    loop: 173,
  },
  {
    file: "evals/tasks/swarm_targets/slow_loop_optimize/bench_loop_opt.py",
    short: "bench_loop_opt.py",
    before: 24,
    after: 20,
    parseMs: 0.19,
    compileMs: 0.1,
    pr: 0,
    inTree: "084a56bf6174",
    status: "in-tree",
    loop: 174,
  },
  {
    file: "tests/test_public_mcp_transport_security.py",
    short: "test_public_mcp_transport_security.py",
    before: 45,
    after: 35,
    parseMs: 0.24,
    compileMs: 0.24,
    pr: 0,
    inTree: "b1a5fcd3729f",
    status: "in-tree",
    loop: 175,
  },
  {
    file: "evals/tasks/swarm_targets/nsquared_dedup/bench_dedup.py",
    short: "bench_dedup.py",
    before: 20,
    after: 20,
    parseMs: 0.22,
    compileMs: 0.13,
    pr: 0,
    inTree: "7d8b8d55eae1",
    status: "in-tree",
    loop: 176,
  },
  {
    file: "evals/tasks/swarm_targets/slow_loop_optimize/test_loop_opt.py",
    short: "test_loop_opt.py",
    before: 19,
    after: 20,
    parseMs: 0.14,
    compileMs: 0.07,
    pr: 0,
    inTree: "1f5bedf5e704",
    status: "in-tree",
    loop: 177,
  },
  {
    file: "tests/fixtures/swarm_target/test_slow.py",
    short: "test_slow.py",
    before: 16,
    after: 20,
    parseMs: 0.18,
    compileMs: 0.09,
    pr: 0,
    inTree: "d0d72f857110",
    status: "in-tree",
    loop: 178,
  },
  {
    file: "tests/test_claude_md_runtime_contract.py",
    short: "test_claude_md_runtime_contract.py",
    before: 15,
    after: 20,
    parseMs: 0.13,
    compileMs: 0.07,
    pr: 0,
    inTree: "e03288150c59",
    status: "in-tree",
    loop: 179,
  },
  {
    file: "evals/tasks/swarm_targets/slow_loop_optimize/loop_opt.py",
    short: "loop_opt.py",
    before: 15,
    after: 20,
    parseMs: 0.13,
    compileMs: 0.05,
    pr: 0,
    inTree: "62c1e9bdd4d0",
    status: "in-tree",
    loop: 180,
  },
  {
    file: "evals/tasks/swarm_targets/nsquared_dedup/dedup.py",
    short: "dedup.py",
    before: 11,
    after: 20,
    parseMs: 0.09,
    compileMs: 0.05,
    pr: 0,
    inTree: "86376bf61eac",
    status: "in-tree",
    loop: 181,
  },
  {
    file: "tests/fixtures/swarm_target/bench_unstable.py",
    short: "bench_unstable.py",
    before: 10,
    after: 20,
    parseMs: 0.13,
    compileMs: 0.07,
    pr: 0,
    inTree: "8b119a6d34ef",
    status: "in-tree",
    loop: 182,
  },
  {
    file: "tests/fixtures/swarm_target/bench_slow.py",
    short: "bench_slow.py",
    before: 10,
    after: 20,
    parseMs: 0.12,
    compileMs: 0.05,
    pr: 0,
    inTree: "f8a4f6026238",
    status: "in-tree",
    loop: 183,
  },
  {
    file: "src/version.py",
    short: "version.py",
    before: 10,
    after: 20,
    parseMs: 0.06,
    compileMs: 0.03,
    pr: 0,
    inTree: "633a08e9d8cf",
    status: "in-tree",
    loop: 184,
  },
  {
    file: "tests/fixtures/swarm_target/test_slow_suite.py",
    short: "test_slow_suite.py",
    before: 9,
    after: 20,
    parseMs: 0.13,
    compileMs: 0.06,
    pr: 0,
    inTree: "310bd927c397",
    status: "in-tree",
    loop: 185,
  },
  {
    file: "tests/fixtures/multifile_pkg/test_policy.py",
    short: "test_policy.py",
    before: 9,
    after: 20,
    parseMs: 0.1,
    compileMs: 0.05,
    pr: 0,
    inTree: "5bfadb9fb2aa",
    status: "in-tree",
    loop: 186,
  },
  {
    file: "src/__init__.py",
    short: "__init__.py",
    before: 9,
    after: 20,
    parseMs: 0.1,
    compileMs: 0.04,
    pr: 0,
    inTree: "6560dd876355",
    status: "in-tree",
    loop: 187,
  },
  {
    file: "tests/fixtures/multifile_pkg/policy.py",
    short: "policy.py",
    before: 7,
    after: 20,
    parseMs: 0.11,
    compileMs: 0.05,
    pr: 0,
    inTree: "87862797d2b9",
    status: "in-tree",
    loop: 188,
  },
  {
    file: "tests/fixtures/multifile_pkg/constants.py",
    short: "constants.py",
    before: 7,
    after: 20,
    parseMs: 0.09,
    compileMs: 0.03,
    pr: 0,
    inTree: "a410f99766ec",
    status: "in-tree",
    loop: 189,
  },
  {
    file: "src/swarm/__init__.py",
    short: "__init__.py",
    before: 7,
    after: 20,
    parseMs: 0.05,
    compileMs: 0.02,
    pr: 0,
    inTree: "e9c5657754ef",
    status: "in-tree",
    loop: 190,
  },
  {
    file: "evals/__init__.py",
    short: "__init__.py",
    before: 7,
    after: 20,
    parseMs: 0.03,
    compileMs: 0.02,
    pr: 0,
    inTree: "be4d9df1acd1",
    status: "in-tree",
    loop: 191,
  },
  {
    file: "tests/fixtures/multifile_pkg/__init__.py",
    short: "__init__.py",
    before: 5,
    after: 20,
    parseMs: 0.07,
    compileMs: 0.03,
    pr: 0,
    inTree: "4705ce414b8c",
    status: "in-tree",
    loop: 192,
  },
  {
    file: "main.py",
    short: "main.py",
    before: 5,
    after: 20,
    parseMs: 0.11,
    compileMs: 0.04,
    pr: 0,
    inTree: "0074ddbccc12",
    status: "in-tree",
    loop: 193,
  },
  {
    file: "tests/fixtures/swarm_target/test_nocov.py",
    short: "test_nocov.py",
    before: 3,
    after: 20,
    parseMs: 0.1,
    compileMs: 0.03,
    pr: 0,
    inTree: "0a0afa6d10c4",
    status: "in-tree",
    loop: 194,
  },
  {
    file: "src/tools/__init__.py",
    short: "__init__.py",
    before: 2,
    after: 20,
    parseMs: 0.04,
    compileMs: 0.02,
    pr: 0,
    inTree: "dbeb7893fec2",
    status: "in-tree",
    loop: 195,
  },
  {
    file: "tests/__init__.py",
    short: "__init__.py",
    before: 1,
    after: 20,
    parseMs: 0.04,
    compileMs: 0.02,
    pr: 0,
    inTree: "14aa89fbd841",
    status: "in-tree",
    loop: 196,
  },
  {
    file: "scripts/__init__.py",
    short: "__init__.py",
    before: 1,
    after: 20,
    parseMs: 0.06,
    compileMs: 0.02,
    pr: 0,
    inTree: "bb47f0d18f01",
    status: "in-tree",
    loop: 197,
  },
  {
    file: "tests/.../__init__.py",
    short: "__init__.py",
    before: 0,
    after: 20,
    parseMs: 0.02,
    compileMs: 0.01,
    pr: 0,
    inTree: "84cb7076262a",
    status: "in-tree",
    loop: 198,
  },
  {
    file: "tests/campaigns/__init__.py",
    short: "__init__.py",
    before: 0,
    after: 20,
    parseMs: 0.02,
    compileMs: 0.01,
    pr: 0,
    inTree: "d66c36ad11c7",
    status: "in-tree",
    loop: 199,
  },
  {
    file: "evals/.../__init__.py",
    short: "__init__.py",
    before: 0,
    after: 20,
    parseMs: 0.03,
    compileMs: 0.02,
    pr: 0,
    inTree: "ae4437932cb7",
    status: "in-tree",
    loop: 200,
  },
  {
    file: "evals/campaigns/__init__.py",
    short: "__init__.py",
    before: 0,
    after: 20,
    parseMs: 0.02,
    compileMs: 0.02,
    pr: 0,
    inTree: "bda882ffbf6e",
    status: "in-tree",
    loop: 201,
  },
];

const TOTAL_INVENTORY = 210;
const SNAPSHOT = "Tracker 2026-07-16T17:28:04Z · projected facade/shim LOC · pending 0";

function pctChange(before: number, after: number): number {
  if (before <= 0) return 0;
  return ((after - before) / before) * 100;
}

function fmtPct(p: number): string {
  const sign = p > 0 ? "+" : "";
  return `${sign}${p.toFixed(1)}%`;
}

function fmtLoc(n: number): string {
  return n.toLocaleString("en-US");
}

function pctTone(
  p: number,
): "success" | "warning" | "danger" | "neutral" | "info" {
  if (p <= -40) return "success";
  if (p <= -10) return "info";
  if (p < 5 && p > -5) return "neutral";
  if (p >= 5) return "danger";
  return "warning";
}

function pctColor(
  p: number,
  theme: ReturnType<typeof useHostTheme>,
): string {
  if (p <= -40) return theme.category.green;
  if (p <= -10) return theme.category.cyan;
  if (p < 5 && p > -5) return theme.text.tertiary;
  if (p >= 5) return theme.category.red;
  return theme.category.yellow;
}

type SortMode = "biggest_win" | "loc_before" | "pr";
type ViewMode = "ready" | "all";

export default function PythonSuperiorityLoopMetrics() {
  const theme = useHostTheme();
  const [sort, setSort] = useCanvasState<SortMode>("sort", "biggest_win");
  const [view, setView] = useCanvasState<ViewMode>("view", "ready");
  const [showChart, setShowChart] = useCanvasState("showChart", true);

  const withPct = FILES.map((f) => ({
    ...f,
    pct: pctChange(f.before, f.after),
    delta: f.after - f.before,
    latMs: f.parseMs + f.compileMs,
  }));

  const readyOnly = view === "ready";
  const filtered = readyOnly
    ? withPct.filter((f) => f.status === "Ready" || f.status === "in-tree")
    : withPct;

  const sorted = [...filtered].sort((a, b) => {
    if (sort === "biggest_win") return a.pct - b.pct;
    if (sort === "loc_before") return b.before - a.before;
    return (a.pr || 9999) - (b.pr || 9999);
  });

  const totalBefore = withPct.reduce((s, f) => s + f.before, 0);
  const totalAfter = withPct.reduce((s, f) => s + f.after, 0);
  const overallPct = pctChange(totalBefore, totalAfter);
  const avgPct =
    withPct.reduce((s, f) => s + f.pct, 0) / Math.max(withPct.length, 1);
  const readyCount = withPct.filter((f) => f.status === "Ready").length;
  const inTreeCount = withPct.filter((f) => f.status === "in-tree").length;
  const doneCount = FILES.length;
  const pendingCount = TOTAL_INVENTORY - doneCount - 9;
  const skippedCount = 9;
  const progressPct = (doneCount / TOTAL_INVENTORY) * 100;

  const chartTop = [...withPct]
    .sort((a, b) => b.before - a.before)
    .slice(0, 8);

  const topWins = [...withPct].sort((a, b) => a.pct - b.pct).slice(0, 5);

  return (
    <Stack
      gap={24}
      style={{
        padding: 28,
        background: theme.bg.editor,
        minHeight: "100%",
      }}
    >
      <Stack gap={8}>
        <Row gap={10} align="center">
          <Text size="small" tone="secondary" weight="semibold">
            Cursor × UniGrok
          </Text>
          <Pill size="sm" active>
            Python Superiority Loop
          </Pill>
          <Spacer />
          <Text size="small" tone="tertiary">
            {SNAPSHOT}
          </Text>
        </Row>
        <H1>Projected LOC cut — live % board</H1>
        <Text tone="secondary">
          Before → after facade/shim projections from the superiority-loop
          tracker. Green = reduction. Inventory pending = 0; full done set
          of refactor plans. Codex Sol High can watch Ready drafts; merge
          stays the normal Codex land path.
        </Text>
      </Stack>

      <Grid columns={4} gap={16}>
        <Stat
          value={fmtPct(overallPct)}
          label="Overall LOC reduction"
          tone="success"
        />
        <Stat
          value={fmtPct(avgPct)}
          label="Avg file % cut"
          tone="info"
        />
        <Stat
          value={`${doneCount} / ${TOTAL_INVENTORY}`}
          label="Files with plans"
          tone="info"
        />
        <Stat
          value={String(readyCount)}
          label="Ready draft PRs"
          tone="info"
        />
      </Grid>

      <Card>
        <CardHeader trailing={`${progressPct.toFixed(0)}% of inventory`}>
          Loop progress
        </CardHeader>
        <CardBody>
          <Stack gap={12}>
            <UsageBar
              total={TOTAL_INVENTORY}
              topLeftLabel={`${doneCount} plans done`}
              topRightLabel={`${pendingCount} pending · ${skippedCount} skipped · ${TOTAL_INVENTORY} total`}
              segments={[
                { id: "ready", value: doneCount, color: "green" },
                { id: "skipped", value: skippedCount, color: "yellow" },
                { id: "pending", value: pendingCount, color: "gray" },
              ]}
            />
            <Row gap={16} wrap>
              <Text size="small" tone="secondary">
                LOC {fmtLoc(totalBefore)} → {fmtLoc(totalAfter)} (
                {fmtLoc(totalAfter - totalBefore)} lines)
              </Text>
              <Text size="small" tone="tertiary">
                Next pending: none · {inTreeCount} in-tree plans on
                cursor/python-superiority-loop
              </Text>
            </Row>
          </Stack>
        </CardBody>
      </Card>

      <Stack gap={8}>
        <H2>Biggest % wins</H2>
        <Grid columns={5} gap={12}>
          {topWins.map((f) => (
            <div key={f.pr || f.inTree || f.file}>
              <Card size="lg">
                <CardHeader trailing={f.pr ? `#${f.pr}` : "in-tree"}>{f.short}</CardHeader>
                <CardBody>
                  <Stack gap={4}>
                    <Text
                      weight="bold"
                      style={{
                        fontSize: 22,
                        color: pctColor(f.pct, theme),
                        lineHeight: 1.2,
                      }}
                    >
                      {fmtPct(f.pct)}
                    </Text>
                    <Text size="small" tone="secondary">
                      {fmtLoc(f.before)} → {fmtLoc(f.after)} LOC
                    </Text>
                  </Stack>
                </CardBody>
              </Card>
            </div>
          ))}
        </Grid>
      </Stack>

      <Stack gap={10}>
        <Row gap={12} align="center" wrap>
          <H2>File metrics</H2>
          <Spacer />
          <Row gap={6} align="center">
            <Text size="small" tone="secondary">
              Done only
            </Text>
            <Toggle
              checked={readyOnly}
              onChange={(on) => setView(on ? "ready" : "all")}
            />
          </Row>
          <Row gap={6} align="center">
            <Text size="small" tone="secondary">
              LOC chart
            </Text>
            <Toggle checked={showChart} onChange={setShowChart} />
          </Row>
          <Select
            value={sort}
            onChange={(v) => setSort(v as SortMode)}
            options={[
              { value: "biggest_win", label: "Sort: biggest % win" },
              { value: "loc_before", label: "Sort: LOC before" },
              { value: "pr", label: "Sort: PR #" },
            ]}
          />
        </Row>

        {showChart ? (
          <Stack gap={6}>
            <Text size="small" tone="secondary" weight="semibold">
              Top 8 files — projected LOC before vs after (facade/shim)
            </Text>
            <BarChart
              categories={chartTop.map((f) => f.short)}
              series={[
                {
                  name: "Before LOC",
                  data: chartTop.map((f) => f.before),
                  tone: "warning",
                },
                {
                  name: "After LOC (projected)",
                  data: chartTop.map((f) => f.after),
                  tone: "success",
                },
              ]}
              height={220}
              valueSuffix=" LOC"
              horizontal
              showValues={false}
            />
            <Text size="small" tone="tertiary">
              Source: python-superiority-loop tracker · projected after =
              facade/shim target (modules split out)
            </Text>
          </Stack>
        ) : null}

        <Table
          headers={[
            "File",
            "Before",
            "After",
            "Δ LOC",
            "Δ%",
            "Latency (baseline)",
            "PR",
            "Status",
          ]}
          columnAlign={[
            "left",
            "right",
            "right",
            "right",
            "right",
            "left",
            "left",
            "left",
          ]}
          striped
          stickyHeader
          rowTone={sorted.map((f) => pctTone(f.pct))}
          rows={sorted.map((f) => [
            <Text size="small" as="span" truncate>
              {f.file}
            </Text>,
            fmtLoc(f.before),
            fmtLoc(f.after),
            fmtLoc(f.delta),
            <Text
              as="span"
              weight="semibold"
              size="small"
              style={{ color: pctColor(f.pct, theme) }}
            >
              {fmtPct(f.pct)}
            </Text>,
            `parse ${f.parseMs}ms / compile ${f.compileMs}ms`,
            f.pr ? (
              <Link
                href={`https://github.com/djtelicloud/grok-mcp-server/pull/${f.pr}`}
              >
                #{f.pr}
              </Link>
            ) : (
              <Text size="small" as="span" tone="tertiary">
                in-tree:{f.inTree}
              </Text>
            ),
            f.status === "Ready" ? (
              <Pill size="sm" active>
                Ready
              </Pill>
            ) : f.status === "in-tree" ? (
              <Pill size="sm" active>
                in-tree
              </Pill>
            ) : (
              <Pill size="sm">draft</Pill>
            ),
          ])}
        />
        <Text size="small" tone="tertiary">
          Δ% = (after − before) / before × 100. Latency is current-file
          baseline only — after-parse not recorded in tracker. Memory: n/a
          across this batch. Tiny stubs may show projected growth.
        </Text>
      </Stack>

      <Divider />

      <Callout tone="info" title="Watcher handoff">
        <Text size="small">
          {readyCount} Ready draft PRs (#342–#474, skip #408 docs) plus
          {inTreeCount} in-tree plans on cursor/python-superiority-loop are
          queued for Codex Sol High. Land/merge remains the normal Codex
          supervisor path — this board is visibility only. Pending: 0.
        </Text>
      </Callout>
    </Stack>
  );
}
